spring.application.name=tenpo-dynamic-amount-rest
retry.maxAttempts=3
requestLimit=3
externalServiceUrl=https://jsonplaceholder.typicode.com/posts/

# redis
redis.default.ttl=30
spring.redis.timeout=10s
spring.redis.connect-timeout=10s

# data base
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver
